// ── 50 Zero-Rand Business Ideas ──────────────────────────────────────────────
// Source: inputs/ideas.md — all ideas a young SA entrepreneur can start for free.

export type Category = "business" | "community" | "learn" | "creative" | "tech";

export interface Idea {
  id: string;
  emoji: string;
  name: string;
  nameSA: string;
  description: string;
  descriptionSA: string;
  category: Category;
  earning: string;
}

export const CATEGORY_META: Record<Category, { label: string; labelSA: string; emoji: string; color: string; wash: string }> = {
  business:  { label: "Business",  labelSA: "Besigheid",   emoji: "💼", color: "#22A06B", wash: "#EDF8F2" },
  community: { label: "Community", labelSA: "Gemeenskap",  emoji: "🤝", color: "#38BDF8", wash: "#EFF9FF" },
  learn:     { label: "Learn",     labelSA: "Leer",        emoji: "📚", color: "#D4763C", wash: "#FFFBF0" },
  creative:  { label: "Creative",  labelSA: "Kreatief",    emoji: "🎨", color: "#F472B6", wash: "#FFF0F7" },
  tech:      { label: "Tech",      labelSA: "Tegnologie",  emoji: "💻", color: "#2B8FCC", wash: "#EFF9FF" },
};

export const IDEAS: Idea[] = [
  // ── Business (10) ──────────────────────────────────────────────────────────
  { id: "sneaker-rescue",     emoji: "👟", name: "Sneaker Rescue",        nameSA: "Sneaker-redding",        description: "Premium sneaker cleaning. Advertise via WhatsApp status with before/after photos.",               descriptionSA: "Premium sneaker-skoonmaak. Adverteer via WhatsApp-status met voor/na-foto's.",       category: "business",  earning: "R50–R200/day" },
  { id: "thrift-flipper",     emoji: "👗", name: "Thrift Flipper",        nameSA: "Tweedehandse Mode",      description: "Buy second-hand clothes, wash and style them, sell on Instagram with cool photos.",                descriptionSA: "Koop tweedehandse klere, was en style dit, verkoop op Instagram.",                    category: "business",  earning: "R80–R300/day" },
  { id: "spaza-restock",      emoji: "🛒", name: "Spaza Restock Helper",  nameSA: "Spaza Hervoorraad",      description: "Help local Spaza shops order stock online in bulk, saving them a trip to the wholesaler.",          descriptionSA: "Help plaaslike Spaza-winkels om voorraad aanlyn in grootmaat te bestel.",             category: "business",  earning: "R100–R250/day" },
  { id: "queue-standin",      emoji: "🛵", name: "Queue Stand-in",        nameSA: "Ry-staan Diens",         description: "Get paid to stand in long lines at clinics or SASSA offices for people who have to work.",           descriptionSA: "Kry betaal om in lang rye by klinieke of SASSA-kantore te staan.",                    category: "business",  earning: "R50–R150/day" },
  { id: "late-night-bites",   emoji: "🍔", name: "Late Night Bites",      nameSA: "Aandete Happies",        description: "Sell warm snacks like vetkoek or fries to people walking home late. Promote via WhatsApp group.",    descriptionSA: "Verkoop warm happies soos vetkoek aan mense wat laat huis toe stap.",                category: "business",  earning: "R80–R250/day" },
  { id: "mobile-laundry",     emoji: "🧺", name: "Mobile Laundry",        nameSA: "Mobiele Wasgoed",        description: "Collect laundry, wash it at home or a laundromat, deliver it folded the next day.",                 descriptionSA: "Versamel wasgoed, was dit tuis of by 'n wasserette, lewer dit gevou af.",             category: "business",  earning: "R60–R200/day" },
  { id: "braiding-booker",    emoji: "💇🏾‍♀️", name: "Braiding Booker",      nameSA: "Vlegsel Boeking",        description: "WhatsApp catalog where people can see hairstyles and book appointments with local braiders.",        descriptionSA: "WhatsApp-katalogus waar mense haarstyle kan sien en afsprake maak.",                 category: "business",  earning: "R100–R400/day" },
  { id: "eco-car-wash",       emoji: "🚗", name: "Eco Car Wash",          nameSA: "Eko Motorwas",           description: "Water-saving car wash service that comes to the client's house on weekends.",                       descriptionSA: "Waterbesparende motorwasdiens wat naweke by die kliënt se huis kom.",                 category: "business",  earning: "R80–R300/day" },
  { id: "fresh-veggie-box",   emoji: "🍅", name: "Fresh Veggie Box",      nameSA: "Vars Groenteboks",       description: "Buy veggies in bulk from the city market and deliver mixed, affordable veggie boxes locally.",       descriptionSA: "Koop groente in grootmaat en lewer bekostigbare groentebokse plaaslik af.",           category: "business",  earning: "R100–R350/day" },
  { id: "airtime-reseller",   emoji: "📱", name: "Airtime/Data Reseller", nameSA: "Lugtyd/Data Herverkoper", description: "Buy airtime/data in bulk and resell it to neighbors late at night when shops are closed.",           descriptionSA: "Koop lugtyd/data in grootmaat en herverkoop dit laat snags.",                         category: "business",  earning: "R40–R150/day" },

  // ── Community (10) ─────────────────────────────────────────────────────────
  { id: "clinic-tracker",     emoji: "🏥", name: "Clinic Line Tracker",   nameSA: "Kliniek Ry-tracker",     description: "WhatsApp group with live updates on how long the line is at the local clinic.",                     descriptionSA: "WhatsApp-groep met regstreekse opdaterings oor die ry by die plaaslike kliniek.",     category: "community", earning: "R30–R80/day" },
  { id: "lost-found-bot",     emoji: "🔍", name: "Lost & Found Bot",      nameSA: "Verloor & Gevind",       description: "A page or WhatsApp group dedicated to finding lost ID books and keys in your area.",                descriptionSA: "'n Bladsy of groep gewy om verlore ID-boeke en sleutels te vind.",                   category: "community", earning: "R20–R60/day" },
  { id: "safety-alert",       emoji: "🚨", name: "Safety Alert Network",  nameSA: "Veiligheid Waarskuwings", description: "Fast-alert WhatsApp system for your street to warn about crime or emergencies.",                    descriptionSA: "Vinnige WhatsApp-waarskuwingstelsel vir jou straat oor misdaad of noodgevalle.",      category: "community", earning: "R40–R100/day" },
  { id: "water-power-update", emoji: "💧", name: "Water/Power Updates",   nameSA: "Water/Krag Opdaterings", description: "Be the reliable source for loadshedding and water outage updates for your neighborhood.",            descriptionSA: "Wees die betroubare bron vir beurtkrag- en wateronderbrekings-opdaterings.",          category: "community", earning: "R30–R80/day" },
  { id: "fix-it-match",       emoji: "🛠️", name: "Local Fix-it Match",    nameSA: "Plaaslike Herstel-diens", description: "Connect people who fix pipes or roofs with neighbors who need help, for a finder's fee.",            descriptionSA: "Verbind mense wat pype of dakke herstel met bure wat hulp nodig het.",                category: "community", earning: "R50–R200/day" },
  { id: "trusted-babysitters", emoji: "👶", name: "Trusted Babysitters",  nameSA: "Betroubare Oppassers",   description: "Create a network of trusted, verified teenagers who can watch kids when parents work late.",         descriptionSA: "Skep 'n netwerk van betroubare tieners wat kinders kan oppas.",                       category: "community", earning: "R50–R150/day" },
  { id: "walking-school-bus", emoji: "🚶🏾‍♂️", name: "Walking School Bus",   nameSA: "Loop-skoolbus",          description: "Safely walk a group of younger kids to and from school every day.",                                 descriptionSA: "Loop veilig 'n groep jonger kinders skool toe en terug.",                             category: "community", earning: "R40–R120/day" },
  { id: "street-clean-crew",  emoji: "🧹", name: "Street Clean Crew",     nameSA: "Straat Skoonmaak Span",  description: "Organize weekend clean-ups. Sell the recyclable plastic, glass, and cans for profit.",               descriptionSA: "Organiseer naweek-skoonmaak. Verkoop herwinbare plastiek, glas en blikkies.",         category: "community", earning: "R60–R180/day" },
  { id: "weekend-tournament", emoji: "⚽", name: "Weekend Tournament",    nameSA: "Naweek Toernooi",        description: "Organize local 5-a-side soccer or netball tournaments. Charge entry and get a sponsor.",             descriptionSA: "Organiseer plaaslike 5-a-kant sokker- of netbaltoernooie.",                           category: "community", earning: "R100–R400/day" },
  { id: "community-garden",   emoji: "🌱", name: "Community Garden",      nameSA: "Gemeenskap Tuin",        description: "Turn an empty patch into a veggie garden. Sell the fresh produce to neighbors.",                     descriptionSA: "Maak 'n leë stuk grond 'n groentetuin. Verkoop vars produkte aan bure.",              category: "community", earning: "R50–R200/day" },

  // ── Learn (10) ─────────────────────────────────────────────────────────────
  { id: "math-ai-buddy",      emoji: "🤖", name: "Math AI Buddy",         nameSA: "Wiskunde AI Maat",       description: "Set up a free WhatsApp bot using ChatGPT that explains difficult math homework to students.",        descriptionSA: "Stel 'n gratis WhatsApp-bot op wat moeilike wiskunde-huiswerk verduidelik.",          category: "learn",     earning: "R30–R100/day" },
  { id: "cv-creator",         emoji: "📄", name: "CV Creator",            nameSA: "CV Skepper",             description: "Help older folks or school leavers create professional CVs on your phone using Canva.",              descriptionSA: "Help ouer mense of skoolverlaters om professionele CV's op jou foon te maak.",       category: "learn",     earning: "R40–R150/day" },
  { id: "textbook-swap",      emoji: "📚", name: "Textbook Swap",         nameSA: "Handboek Ruil",          description: "Run a platform where students can swap or buy cheap second-hand school books.",                     descriptionSA: "Bestuur 'n platform waar studente tweedehandse skoolboeke kan ruil of koop.",         category: "learn",     earning: "R30–R100/day" },
  { id: "bursary-finder",     emoji: "🎓", name: "Bursary Finder",        nameSA: "Beurs Soeker",           description: "Find scholarships online and help local students fill out applications.",                           descriptionSA: "Vind beurse aanlyn en help plaaslike studente met aansoeke.",                         category: "learn",     earning: "R50–R200/day" },
  { id: "language-tutor",     emoji: "🗣️", name: "English/Xhosa Tutor",   nameSA: "Taal Tutor",             description: "Offer 30-minute language practice sessions over WhatsApp voice notes for beginners.",                descriptionSA: "Bied 30-minuut taaloefensessies oor WhatsApp-stemnote aan.",                         category: "learn",     earning: "R40–R120/day" },
  { id: "phone-coding-club",  emoji: "💻", name: "Phone Coding Club",     nameSA: "Foon Kodeerklas",        description: "Teach younger kids how to build basic websites using just their smartphone browsers.",               descriptionSA: "Leer jonger kinders hoe om basiese webwerwe op hul slimfone te bou.",                category: "learn",     earning: "R50–R150/day" },
  { id: "interview-prep",     emoji: "🎤", name: "Interview Prep",        nameSA: "Onderhoud Voorbereiding", description: "Do mock job interviews via video call to help people gain confidence.",                              descriptionSA: "Doen skyn-onderhoude via video-oproep om mense selfvertroue te gee.",                 category: "learn",     earning: "R40–R120/day" },
  { id: "story-time",         emoji: "📖", name: "Story Time App",        nameSA: "Storietyd",              description: "Record audio of yourself reading children's books and share with busy parents.",                    descriptionSA: "Neem oudio op van jouself wat kinderboeke lees en deel met besige ouers.",            category: "learn",     earning: "R20–R80/day" },
  { id: "local-tour-guide",   emoji: "🌍", name: "Local Tour Guide",      nameSA: "Plaaslike Toergids",     description: "Learn the deep history of your township and offer safe, authentic walking tours to tourists.",        descriptionSA: "Leer die diep geskiedenis van jou township en bied veilige toere vir toeriste.",     category: "learn",     earning: "R100–R400/day" },
  { id: "study-group-boss",   emoji: "🧠", name: "Study Group Boss",      nameSA: "Studiegroep Leier",      description: "Organize quiet, focused study sessions in a local church or hall before exams.",                     descriptionSA: "Organiseer stil, gefokusde studiesessies in 'n plaaslike kerk of saal.",              category: "learn",     earning: "R30–R100/day" },

  // ── Creative (10) ──────────────────────────────────────────────────────────
  { id: "flyer-designer",     emoji: "🎨", name: "Flyer Designer",        nameSA: "Pamflet Ontwerper",      description: "Use Canva on your phone to design professional posters for parties, funerals, or churches.",          descriptionSA: "Gebruik Canva op jou foon om professionele plakkate vir partytjies te ontwerp.",      category: "creative",  earning: "R50–R200/day" },
  { id: "beat-maker",         emoji: "🎵", name: "Beat Maker",            nameSA: "Ritme Maker",            description: "Make music beats on your phone using free apps and sell them to local upcoming rappers.",             descriptionSA: "Maak musiekritmes op jou foon met gratis toepassings.",                              category: "creative",  earning: "R40–R300/day" },
  { id: "product-photographer", emoji: "📸", name: "Product Photographer", nameSA: "Produk Fotograaf",       description: "Take high-quality photos of local food stalls or shops with your phone to help them look pro.",       descriptionSA: "Neem hoëgehalte foto's van plaaslike stalletjies met jou foon.",                      category: "creative",  earning: "R60–R250/day" },
  { id: "tiktok-editor",      emoji: "🎬", name: "TikTok Editor",         nameSA: "TikTok Redigeerder",     description: "Edit cool, fast-paced TikTok or Reel videos for small businesses to get more customers.",            descriptionSA: "Redigeer cool TikTok- of Reel-video's vir klein besighede.",                         category: "creative",  earning: "R50–R200/day" },
  { id: "whatsapp-stickers",  emoji: "😂", name: "WhatsApp Stickers",     nameSA: "WhatsApp Plakkers",      description: "Create funny, local WhatsApp stickers with township slang and sell custom packs.",                   descriptionSA: "Skep snaakse WhatsApp-plakkers met township-slang en verkoop dit.",                   category: "creative",  earning: "R20–R80/day" },
  { id: "township-podcast",   emoji: "🎙️", name: "Township Podcast",      nameSA: "Township Podgooi",       description: "Start a podcast using voice notes, interviewing local heroes and sharing real stories.",              descriptionSA: "Begin 'n podgooi met stemnote, ondervra plaaslike helde en deel ware stories.",       category: "creative",  earning: "R30–R150/day" },
  { id: "custom-tshirts",     emoji: "👕", name: "Custom T-Shirts",       nameSA: "Pasgemaakte T-hemde",    description: "Take orders for custom printed shirts for birthdays or events. Outsource printing, keep profit.",     descriptionSA: "Neem bestellings vir pasgemaakte hemde. Uitkontrakteer drukwerk, hou wins.",          category: "creative",  earning: "R60–R250/day" },
  { id: "upcycled-jewelry",   emoji: "💍", name: "Upcycled Jewelry",      nameSA: "Hergebruikte Juweliersware", description: "Make beautiful bracelets or necklaces from wire, beads, or recycled materials.",                 descriptionSA: "Maak pragtige armbande of halssnoere van draad, krale of hergebruikte materiaal.",    category: "creative",  earning: "R40–R200/day" },
  { id: "poetry-rap-blog",    emoji: "📝", name: "Poetry/Rap Blog",       nameSA: "Poësie/Rap Blog",        description: "Start an Instagram page featuring short poems or rap lyrics written by local youth.",                descriptionSA: "Begin 'n Instagram-bladsy met kort gedigte of raplirieke deur plaaslike jeug.",       category: "creative",  earning: "R20–R100/day" },
  { id: "nail-art-pro",       emoji: "💅🏽", name: "Nail Art Pro",          nameSA: "Naelkuns Pro",           description: "Do amazing, creative nail art from your home using cheap supplies and promote on TikTok.",           descriptionSA: "Doen kreatiewe naelkuns van jou huis af en bevorder dit op TikTok.",                  category: "creative",  earning: "R60–R300/day" },

  // ── Tech (10) ──────────────────────────────────────────────────────────────
  { id: "digital-menu-maker", emoji: "🌐", name: "Digital Menu Maker",    nameSA: "Digitale Spyskaart",     description: "Turn paper menus from food stalls into QR codes people can scan with their phones.",                descriptionSA: "Maak papier-spyskaarte oor na QR-kodes wat mense met hul fone kan skandeer.",        category: "tech",      earning: "R50–R150/day" },
  { id: "social-media-mgr",   emoji: "📱", name: "Social Media Manager",  nameSA: "Sosiale Media Bestuurder", description: "Manage the Facebook and Instagram pages for 3 local businesses. Charge a small weekly fee.",       descriptionSA: "Bestuur die Facebook- en Instagram-bladsye vir 3 plaaslike besighede.",               category: "tech",      earning: "R60–R250/day" },
  { id: "wifi-map-maker",     emoji: "📍", name: "Wi-Fi Map Maker",       nameSA: "Wi-Fi Kaart Maker",      description: "Create a digital list or map of all spots with free or cheap Wi-Fi in the area.",                   descriptionSA: "Skep 'n digitale lys of kaart van alle plekke met gratis of goedkoop Wi-Fi.",        category: "tech",      earning: "R30–R80/day" },
  { id: "digital-receipts",   emoji: "🧾", name: "Digital Receipts",      nameSA: "Digitale Kwitansies",    description: "Help local plumbers or builders send professional digital invoices using free apps.",                descriptionSA: "Help plaaslike loodgieters om professionele digitale fakture te stuur.",              category: "tech",      earning: "R40–R120/day" },
  { id: "online-surveys",     emoji: "📊", name: "Online Survey Filler",  nameSA: "Aanlyn Opname Vuller",   description: "Sign up for platforms where you get paid to fill out surveys and test new apps.",                    descriptionSA: "Registreer by platforms waar jy betaal word om opnames in te vul en toepassings te toets.", category: "tech", earning: "R20–R80/day" },
  { id: "link-in-bio",        emoji: "🔗", name: "Link-in-Bio Setup",     nameSA: "Skakel-in-Bio Opstelling", description: "Build simple Linktree-style pages for local influencers or businesses using free tools.",          descriptionSA: "Bou eenvoudige Linktree-styl bladsye vir plaaslike beïnvloeders.",                   category: "tech",      earning: "R40–R150/day" },
  { id: "auto-reply-bot",     emoji: "🤖", name: "Auto-Reply Bot",        nameSA: "Outo-Antwoord Bot",      description: "Set up WhatsApp Business auto-replies for busy salons so they don't miss clients.",                 descriptionSA: "Stel WhatsApp Business outo-antwoorde op sodat besige salonne nie kliënte mis nie.", category: "tech",      earning: "R50–R200/day" },
  { id: "glide-app-shop",     emoji: "🛒", name: "Glide App Shop",        nameSA: "Glide Toep Winkel",      description: "Use GlideApp to turn a Google Sheet into a real shopping app for a local grocery store.",            descriptionSA: "Gebruik GlideApp om 'n Google Sheet in 'n ware winkeltoep te verander.",              category: "tech",      earning: "R60–R250/day" },
  { id: "digital-tickets",    emoji: "🎟️", name: "Digital Tickets",       nameSA: "Digitale Kaartjies",     description: "Use a simple online form to sell digital tickets for local parties, avoiding fake paper tickets.",     descriptionSA: "Gebruik 'n eenvoudige aanlyn vorm om digitale kaartjies vir partytjies te verkoop.", category: "tech",      earning: "R40–R150/day" },
  { id: "google-maps-lister", emoji: "📈", name: "Google Maps Lister",    nameSA: "Google Maps Lysmaker",   description: "Get paid to add local, hidden businesses to Google Maps so customers outside can find them.",        descriptionSA: "Kry betaal om plaaslike besighede op Google Maps te sit.",                            category: "tech",      earning: "R30–R120/day" },
];
